---
name: build

defaults:
  run:
    shell: bash

on:
  push:

jobs:
  # https://github.com/golangci/golangci-lint-action
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17'
    - run: go version
    - run: go test ./...

  version:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    outputs:
      release-version: ${{ steps.parse.outputs.release-version }}
    runs-on: ubuntu-latest
    steps:
    - id: parse
      env:
        GITHUB_REF: ${{ github.ref }}
      name: Parse version from tag ${{ github.ref }}
      run: |
        if [[ "${GITHUB_REF}" =~ ^refs/tags/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          echo "::set-output name=release-version::${BASH_REMATCH[1]}"
        fi
